---
- name: Package installation
  ansible.builtin.package:
    name: nginx
    state: latest

- name: Deploy Nginx configuration
  template:
    src: nginx.j2
    dest: "/etc/nginx/conf.d/po_app.conf"
  notify: Reload nginx

- name: Start and enable nginx
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: nginx

- name: Setup Certbot renewal cron job
  ansible.builtin.cron:
    name: "Certbot Automatic Renewal"
    job: "/opt/certbot/bin/python -c 'import random; import time; time.sleep(random.random() * 3600)' && sudo certbot renew -q"
    minute: "0"
    hour: "0,12"
    user: root
  when: ssl_cert_path | bool