---
- name: Get packages
  ansible.builtin.package_facts:
  check_mode: false

- name: Get services
  ansible.builtin.service_facts:
  check_mode: false

- name: Install yum-utils
  ansible.builtin.dnf:
    name: yum-utils
    state: installed
  check_mode: false

- name: Upgrade packages (dnf)
  ansible.builtin.dnf:
    name: '*'
    state: latest
    exclude: "{{ exclude_packages }}"
  when: ansible_pkg_mgr == "dnf"
  register: patch_linux_patchingresult_dnf

- name: Check to see if we need a reboot
  ansible.builtin.command: needs-restarting -r
  register: patch_linux_result
  changed_when: patch_linux_result.rc == 1
  failed_when: patch_linux_result.rc > 1
  check_mode: false

- name: Reboot Server if Necessary
  ansible.builtin.reboot:
  when:
    - patch_linux_result.rc == 1
    - allow_reboot
