$ANSIBLE_VAULT;1.1;AES256
36386134363465323430376162323265663363663036653761623663356663666564356130356436
6666633965306534373930616635373465623839663039650a646435656362633434323334613336
65616533623432633332653661386262646634343530626166376163623766663366643331343336
6134346438653135360a393039343331326664376530613365636639656533386639396435633364
31666330326164366531373835366637633632646364666635363266653932356532356338646236
36303030633233643462636231373237663236643432656164663433646236623039616237373666
33613165386535393638346161326337343032313637616633356139636565336264363533346631
34376562373630636562643830633330666362323166346331353536653635346230643632316566
31373535333635633862346236356662623136633131323237363331323730343539
